### PR TITLE
FIX 'Description' error

### PR DESCRIPTION
**Pull request by ironman771**
Fix "show['Description']" error in default.py

### CODE REVIEW

**Comment by nx-99** [comment]
It's work, thank you very much.

**Comment by NeverWise** [comment]
Thanks for your help! Very appreciated!

**Comment by andremanz8** [comment]
No luck. I've tried this last update, now the plugin lists all the tv series, but if I try to load any of these (I.E. "5 gemelle sotto un tetto") the list is poor (it displays only one episode and on dplay there where about 100) and if I try to play it, I have the old "internet connection error".
[kodi.log](https://github.com/NeverWise/plugin.video.dplay/files/2619394/kodi.log)

**Comment by NeverWise** [comment]
Thanks to the help of @davide-acanfora now should works (in my kodi I can see the video).
It's shown only one episode because some video need a dplay account to be play and for now this plugin doesn't manage it.

**Pull request merged**
